# Generated by Django 4.2.9 on 2024-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
